run:
  timeout: 5m 

linters-settings:
  nolintlint:
    allow-: false # report any  nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to mention the specific linter being suppressed:
    ignore-tests: true
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - (context.Context).Err()
  goheader:
    template-path: '.golangci.goheader.template'
    values:
      regexp:
        copyright-year: 20[2-9]\d

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    # - depguard
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    # - exhaustivestruct
    # - forbidigo
    # - forcetypeassert
    # - funlen
    - gocritic
    - gocyclo
    # - cyclop # not interested in package complexities at the moment
    - godot
    - gofmt
    - gofumpt
    - goimports
    - revive
    # - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    # - ifshort
    - ineffassign
    - importas
    # - lll
    # - misspell
    - makezero
    - nakedret
    - nilerr
    - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    # - paralleltest
    - predeclared
    - rowserrcheck
    - staticcheck
    - stylecheck
    - sqlclosecheck
    # - tagliatelle
    # - tenv
    # - thelper
    # - tparallel
    - typecheck
    - unconvert
    # - unparam
    - wastedassign
    - whitespace
    # - wrapcheck
    # - wsl
    - gochecknoinits
    - godot
    - gocheckcompilerdirectives
    - gocognit
    - grouper
    - interfacebloat
    - importas
    - tenv
    - mirror
    - musttag
    - nestif
    - unparam
    - loggercheck
    - maintidx
    - nosprintfhostport
    - prealloc
    - promlinter
    - reassign
    - testableexamples
    - usestdlibvars
    - zerologlint